### ISSUE TITLE
前辈 请求推荐歌曲列表的时候有个需要配置请求头的问题

### ISSUE THREAD

**Issue by huabingtao** [biaodigit/vue-music#4]
本人菜鸟很茫然啊 老师的build目录下有个 dev-server.js 然鹅新的vue 脚手架没带这个文件 所以也不知道怎么才能访问到那个推荐列表的接口 希望老哥指导一下 谢谢！！！不胜感激

**Comment by biaodigit** [comment]
你去看他的源码啊

**Comment by huabingtao** [comment]
我要能看得到源码也不会来问你了呀
